library("quantmod")
getSymbols("GOOG")
head(GOOG)
getSymbols(c("GOOG", "MSFT", "IBM"))
data1<-cbind(GOOG, MSFT, IBM)
head(data1)
tail(data1)
data1<-data1[,c(-1:-3, -5:-10)]
head(data1)
plot(data1$GOOG.Close)
plot(data1[,1])
lines(data1[,7], col="red")
plot(GOOG[,"GOOG.Close"], main="Close")
candleChart(GOOG, up.col="red", dn.col= "blue", theme="white")
